# Generated by Django 5.2.11 on 2026-03-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_inn_company_company_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn_supplier', models.CharField(blank=True, max_length=12, unique=True)),
                ('title', models.CharField(blank=True, max_length=50, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='company.company')),
            ],
        ),
    ]
